"use client"
import Sidebaar from '../template/Sidebaar';
import 'bootstrap/dist/css/bootstrap.min.css';
import { React,useState } from 'react';
import $ from "jquery";
import Header from '../template/Header';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHouse } from '@fortawesome/free-solid-svg-icons'

const Addmore=()=>{


      const sideCanvasActive= () =>{ 
            $(".expovent__sidebar").removeClass("collapsed");
            $(".expovent__sidebar").removeClass("open");
            $(".app__offcanvas-overlay").removeClass("overlay-open");
        
      }
 return(
    <>
      <div className='page_-full-wrapper'>
           <Sidebaar/>
            <div className="app__offcanvas-overlay" onClick={sideCanvasActive}></div>
              <div className="page__body-wrapper">
               <Header/>
               <div className="app__slide-wrapper">
                    <div className="row">
                        <div className="col-xl-12">
                            <div className="breadcrumb__wrapper">
                                <div className="breadcrumb__inner">
                                    <div className="breadcrumb__icon">
                                    <FontAwesomeIcon icon={faHouse}/>
                                    </div>
                                    <div className="breadcrumb__menu">
                                        <nav>
                                        <ul>
                                            <li><span><a href="#">Home</a></span></li>
                                            <li className="active"><span>Add More</span></li>
                                        </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='row'>
                      <div className='col-md-12'>
                         <div className='add-more-form'>
                             <form>
                                <div className='row'>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Lead Generated by</level>
                                         <input type='text' placeholder='Lead Generated by'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Lead Generated For</level>
                                         <input type='text' placeholder='Lead Generated For'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Lead Date</level>
                                         <input type='text' placeholder='Lead Date'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Client Name</level>
                                         <input type='text' placeholder='Client Name'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Email ID*</level>
                                         <input type='text' placeholder='Email ID*'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Website URL</level>
                                         <input type='text' placeholder='Website URL'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Contact Number</level>
                                         <input type='text' placeholder='Contact Number'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Services</level>
                                         <input type='text' placeholder='Contact Number'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Industry</level>
                                         <input type='text' placeholder='Industry'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Country</level>
                                         <input type='text' placeholder='Country'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <level>Generated from Domain/General Ids</level>
                                         <input type='text' placeholder='Generated from Domain/General Ids'/>
                                      </div>
                                   </div>
                                   <div className='col-md-6'>
                                      <div className='form-group'>
                                         <button>Save</button>
                                      </div>
                                   </div>
                                </div>
                             </form>
                         </div>
                      </div>
                    </div>
                </div>
              </div>
         </div>
    </>
 )


}
export default Addmore