"use client"

import 'bootstrap/dist/css/bootstrap.min.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHouse } from '@fortawesome/free-solid-svg-icons'
import $ from "jquery";
import { React,useState, useEffect } from 'react';
import Table from 'react-bootstrap/Table';
import Sidebaar from '../template/Sidebaar';
import Header from '../template/Header';
import Link from "next/link"
import Pagination from 'react-bootstrap/Pagination';
import axios from 'axios';

const Dashbord=()=>{
    const sideCanvasActive= () =>{ 
        $(".expovent__sidebar").removeClass("collapsed");
        $(".expovent__sidebar").removeClass("open");
        $(".app__offcanvas-overlay").removeClass("overlay-open");
    
    }
    const [sideBarAccess, setSideBarAccess] = useState({
        users: false
    });
    const [serviceStoreData, setServiceStoreData] = useState([]);
    let active = 2;
    let items = [];
    for (let number = 1; number <= 5; number++) {
    items.push(
        <Pagination.Item key={number} active={number === active}>
        {number}
        </Pagination.Item>,
    );
    }
    const getServiceData = async () => {

        axios.get(`${process.env.API_BASE_URL}services.php`)
          .then(res => {
              const data = res.data.serviceData.map((item) => {
                return {
                  id: item.id,
                  name: item.service_name,
                  status: item.status
                }
            }
          )
          setServiceStoreData(data);
        })
        .catch(err => {
         })
     } 
    useEffect(() => {
        if(localStorage && localStorage.length > 0 && localStorage.type && localStorage.type != "user"){
            setSideBarAccess({
                users : true
            })
            getServiceData();
        }

        }, []);
    return(
        
        <>
         <div className='page_-full-wrapper'>
           <Sidebaar/>
            <div className="app__offcanvas-overlay" onClick={sideCanvasActive}></div>
            <div className="page__body-wrapper">
             <Header />
                <div className="body__overlay"></div>
                <div className="app__slide-wrapper">
                    <div className="row">
                        <div className="col-xl-12">
                            <div className="breadcrumb__wrapper">
                                <div className="breadcrumb__inner">
                                    <div className="breadcrumb__icon">
                                    <FontAwesomeIcon icon={faHouse}/>
                                    </div>
                                    <div className="breadcrumb__menu">
                                        <nav>
                                        <ul>
                                            <li><span><a href="#">Home</a></span></li>
                                            <li className="active"><span>Dashboard</span></li>
                                        </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className='row'>
                        <div className='col-xl-12 col-md-12'>
                            <div className='email-serach-box'>
                              <form  className="serach">
                                <input type="text" placeholder="Email"  name="email" value=""/>
                                <button type="button">Search</button>
                                </form>
                              </div>
{                           localStorage && localStorage.type && localStorage.type == 'admin' &&   
                                <div className='add-more'>
                                <Link href='/addmore'>Add More</Link>
                              </div>}
                              <div className='lms-table-wrap'>
                               <Table striped bordered hover >
                                <thead>
                                    <tr>
                                    <th>Lead Generated by</th>
                                    <th>Lead Generated For</th>
                                    <th>Lead Date</th>
                                    <th>Client Name</th>
                                    <th>Email ID*</th>
                                    <th>Website URL</th>
                                    <th>Contact Number </th>
                                    <th>Services</th>
                                    <th>Industry </th>
                                    <th>Country</th>
                                    <th>Generated from Domain/General Ids</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                    <td>1</td>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    <td>@mdo</td>
                                    <td>1</td>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    <td>@mdo</td>
                                    <td>@mdo</td>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    </tr>
                                    <tr>
                                    <td>2</td>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    <td>@fat</td>
                                    <td>2</td>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    <td>@fat</td>
                                    <td>@fat</td>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    </tr>
                                    <tr>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    </tr>
                                    <tr>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    </tr>
                                    <tr>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>3</td>
                                    <td>Larry the Bird</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    <td>@twitter</td>
                                    </tr>
                                </tbody>
                                </Table>
                              </div>
                            <div className='pagination-wrap'>
                                <Pagination>{items}</Pagination>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
        </>
    )
}
export default Dashbord

